name: streakly
description: A focus timer app to build discipline and streaks.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5  # Latest stable
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1  # Compatible with hive ^2.2.3
  build_runner: ^2.4.6
  analyzer: <9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/streacly_logo.png